# Spanner DDL Knowledge Base
# Extracted from official documentation

# Spanner DDL Knowledge Base
# Extracted from official documentation

DDL_SYNTAX_KNOWLEDGE_BASE = [
    {
        "keywords": ["CREATE TABLE", "TABLE"],
        "topic": "CREATE TABLE Syntax",
        "rule": "Full syntax for creating tables in Spanner, including interleaving and constraints.",
        "syntax": """
CREATE TABLE [ IF NOT EXISTS ] table_name ( [
    { column_name data_type [NOT NULL] [ { DEFAULT ( expression ) | AS ( expression ) [ STORED ] | GENERATED BY DEFAULT AS IDENTITY [ ( sequence_option_clause ... ) ] | AUTO_INCREMENT } ] [ PRIMARY KEY ] [ options_def ]
    | location_name STRING(MAX) NOT NULL PLACEMENT KEY
    | table_constraint
    | synonym_definition } [, ... ]
] ) [ PRIMARY KEY ( [column_name [ { ASC | DESC } ], ...] ) ]
[, INTERLEAVE IN [PARENT] table_name [ ON DELETE { CASCADE | NO ACTION } ] ]
[, ROW DELETION POLICY ( OLDER_THAN ( timestamp_column, INTERVAL num_days DAY ) ) ]
[, OPTIONS ( locality_group = 'locality_group_name' ) ]

where:
- data_type is: { scalar_type | array_type | proto_type_name }
- table_constraint is: [ CONSTRAINT constraint_name ] { CHECK ( expression ) | FOREIGN KEY ( column_name [, ... ] ) REFERENCES ref_table ( ref_column [, ... ] ) [ ON DELETE { CASCADE | NO ACTION } ] [ { ENFORCED | NOT ENFORCED } ] }
- sequence_option_clause is: { BIT_REVERSED_POSITIVE | SKIP RANGE skip_range_min, skip_range_max | START COUNTER WITH start_with_counter }
        """,
        "priority": "HIGH"
    },
    {
        "keywords": ["CREATE INDEX", "INDEX"],
        "topic": "CREATE INDEX Syntax",
        "rule": "Full syntax for creating secondary indexes.",
        "syntax": """
CREATE [ UNIQUE ] [ NULL_FILTERED ] INDEX [ IF NOT EXISTS ] index_name
ON table_name ( key_part [, ...] )
[ storing_clause ]
[ where_clause ]
[ , interleave_clause ]
[ OPTIONS ( locality_group = 'locality_group_name' ) ]

where:
- key_part is: column_name [ { ASC | DESC } ]
- storing_clause is: STORING ( column_name [, ...] )
- where_clause is: WHERE column_name IS NOT NULL [AND ...]
- interleave_clause is: INTERLEAVE IN table_name
        """,
        "priority": "HIGH"
    },
    {
        "keywords": ["CREATE SEQUENCE", "SEQUENCE", "AUTO_INCREMENT", "SERIAL"],
        "topic": "CREATE SEQUENCE Syntax",
        "rule": "Syntax for creating sequences, especially for Bit-Reversed Sequences to replace Auto-Increment.",
        "syntax": """
CREATE SEQUENCE [ IF NOT EXISTS ] sequence_name [ sequence_option_clause ... ] [ OPTIONS ( sequence_options ) ]

where sequence_option_clause is:
- BIT_REVERSED_POSITIVE
- SKIP RANGE skip_range_min, skip_range_max
- START COUNTER WITH start_with_counter

Options:
- sequence_kind = 'bit_reversed_positive' (Required for bit-reversed)
        """,
        "priority": "HIGH"
    },
    {
        "keywords": ["CREATE VIEW", "VIEW"],
        "topic": "CREATE VIEW Syntax",
        "rule": "Syntax for creating views. Security type (INVOKER/DEFINER) is important.",
        "syntax": """
{ CREATE VIEW | CREATE OR REPLACE VIEW } view_name
SQL SECURITY { INVOKER | DEFINER }
AS query
        """,
        "priority": "MEDIUM"
    },
    {
        "keywords": ["ALTER TABLE", "ALTER"],
        "topic": "ALTER TABLE Syntax",
        "rule": "Syntax for modifying existing tables.",
        "syntax": """
ALTER TABLE table_name action

where action is:
- ADD SYNONYM synonym
- DROP SYNONYM synonym
- RENAME TO new_table_name [, ADD SYNONYM synonym]
- ADD [ COLUMN ] [ IF NOT EXISTS] column_name data_type [ column_expression ] [ options_def ]
- DROP [ COLUMN ] column_name
- ADD table_constraint
- DROP CONSTRAINT constraint_name
- SET ON DELETE { CASCADE | NO ACTION }
- SET INTERLEAVE IN [ PARENT ] parent_table_name [ ON DELETE { CASCADE | NO ACTION } ]
- ALTER [ COLUMN ] column_name { data_type [ NOT NULL ] [ DEFAULT ( expression ) | ... ] | SET OPTIONS (...) }
- ADD ROW DELETION POLICY (...)
- DROP ROW DELETION POLICY
        """,
        "priority": "MEDIUM"
    },
    {
        "keywords": ["INT", "INTEGER", "VARCHAR", "TEXT", "BOOLEAN", "BLOB", "NUMERIC", "DECIMAL"],
        "topic": "Spanner Data Types",
        "rule": "Valid Spanner Scalar Types.",
        "syntax": """
{ BOOL | INT64 | FLOAT32 | FLOAT64 | NUMERIC | STRING( length ) | JSON | BYTES( length ) | DATE | TIMESTAMP }

length: { int64_value | MAX }
MAX for STRING is 2,621,440 characters.
MAX for BYTES is 10,485,760 bytes.
        """,
        "priority": "HIGH"
    }
]

# Feature Hints for specific deep scenarios
FEATURE_BASED_KNOWLEDGE_BASE = [
    {
        "keywords": ["FOREIGN KEY", "REFERENCES", "INTERLEAVE"],
        "topic": "Interleaving Requirement",
        "rule": "CRITICAL: If the primary key of the child table includes a column that is NOT NULL, and that same column is the prefix (primary key) of the parent table, then it MUST also be NOT NULL in the parent table.",
        "syntax": "Parent: Id INT64 NOT NULL ... Child: Id INT64 NOT NULL ... INTERLEAVE IN PARENT Parent",
        "priority": "CRITICAL"
    }
]

# Deterministic Mapping Rules from Spanner Migration Tool
# Source: https://github.com/GoogleCloudPlatform/spanner-migration-tool
MAPPING_RULES_KNOWLEDGE_BASE = {
    "PostgreSQL": [
        {"source_type": "SERIAL / BIGSERIAL", "spanner_type": "INT64", "note": "Use BIT_REVERSED_SEQUENCE or UUID (STRING(36)) to avoid hotspots."},
        {"source_type": "TEXT", "spanner_type": "STRING(MAX)", "note": "Spanner has no TEXT type."},
        {"source_type": "VARCHAR(n)", "spanner_type": "STRING(n)", "note": ""},
        {"source_type": "NUMERIC", "spanner_type": "NUMERIC", "note": "Spanner NUMERIC precision is (38,9). Verification needed if higher precision required."},
        {"source_type": "TIMESTAMP", "spanner_type": "TIMESTAMP", "note": "Stored in UTC."},
        {"source_type": "JSON / JSONB", "spanner_type": "JSON", "note": ""},
        {"source_type": "BYTEA", "spanner_type": "BYTES(MAX)", "note": ""}
    ],
    "MySQL": [
        {"source_type": "TINYINT / SMALLINT / INT / BIGINT", "spanner_type": "INT64", "note": "All integers map to INT64."},
        {"source_type": "AUTO_INCREMENT", "spanner_type": "INT64 NOT NULL", "note": "Use BIT_REVERSED_SEQUENCE or UUID to avoid hotspots. CRITICAL: PKs must be NOT NULL."},
        {"source_type": "TEXT / LONGTEXT", "spanner_type": "STRING(MAX)", "note": ""},
        {"source_type": "VARCHAR(n)", "spanner_type": "STRING(n)", "note": ""},
        {"source_type": "DECIMAL", "spanner_type": "NUMERIC", "note": "Check precision limits (38,9)."},
        {"source_type": "TIMESTAMP / DATETIME", "spanner_type": "TIMESTAMP", "note": "Timezone handling differs."},
        {"source_type": "BLOB", "spanner_type": "BYTES(MAX)", "note": ""},
        {"source_type": "SET", "spanner_type": "ARRAY<STRING>", "note": "Validation dropped."}
    ]
}
