# Spanner DDL Knowledge Base
# Extracted from official documentation

SPANNER_KNOWLEDGE_BASE = [
    {
        "keywords": ["CREATE TABLE", "TABLE"],
        "topic": "CREATE TABLE Syntax",
        "rule": "Full syntax for creating tables in Spanner, including interleaving and constraints.",
        "syntax": """
CREATE TABLE [ IF NOT EXISTS ] table_name ( [
    { column_name data_type [NOT NULL] [ { DEFAULT ( expression ) | AS ( expression ) [ STORED ] | GENERATED BY DEFAULT AS IDENTITY [ ( sequence_option_clause ... ) ] | AUTO_INCREMENT } ] [ PRIMARY KEY ] [ options_def ]
    | location_name STRING(MAX) NOT NULL PLACEMENT KEY
    | table_constraint
    | synonym_definition } [, ... ]
] ) [ PRIMARY KEY ( [column_name [ { ASC | DESC } ], ...] ) ]
[, INTERLEAVE IN [PARENT] table_name [ ON DELETE { CASCADE | NO ACTION } ] ]
[, ROW DELETION POLICY ( OLDER_THAN ( timestamp_column, INTERVAL num_days DAY ) ) ]
[, OPTIONS ( locality_group = 'locality_group_name' ) ]

where:
- data_type is: { scalar_type | array_type | proto_type_name }
- table_constraint is: [ CONSTRAINT constraint_name ] { CHECK ( expression ) | FOREIGN KEY ( column_name [, ... ] ) REFERENCES ref_table ( ref_column [, ... ] ) [ ON DELETE { CASCADE | NO ACTION } ] [ { ENFORCED | NOT ENFORCED } ] }
- sequence_option_clause is: { BIT_REVERSED_POSITIVE | SKIP RANGE skip_range_min, skip_range_max | START COUNTER WITH start_with_counter }
        """,
        "priority": "HIGH"
    },
    {
        "keywords": ["CREATE INDEX", "INDEX"],
        "topic": "CREATE INDEX Syntax",
        "rule": "Full syntax for creating secondary indexes.",
        "syntax": """
CREATE [ UNIQUE ] [ NULL_FILTERED ] INDEX [ IF NOT EXISTS ] index_name
ON table_name ( key_part [, ...] )
[ storing_clause ]
[ where_clause ]
[ , interleave_clause ]
[ OPTIONS ( locality_group = 'locality_group_name' ) ]

where:
- key_part is: column_name [ { ASC | DESC } ]
- storing_clause is: STORING ( column_name [, ...] )
- where_clause is: WHERE column_name IS NOT NULL [AND ...]
- interleave_clause is: INTERLEAVE IN table_name
        """,
        "priority": "HIGH"
    },
    {
        "keywords": ["CREATE SEQUENCE", "SEQUENCE", "AUTO_INCREMENT", "SERIAL"],
        "topic": "CREATE SEQUENCE Syntax",
        "rule": "Syntax for creating sequences, especially for Bit-Reversed Sequences to replace Auto-Increment.",
        "syntax": """
CREATE SEQUENCE [ IF NOT EXISTS ] sequence_name [ sequence_option_clause ... ] [ OPTIONS ( sequence_options ) ]

where sequence_option_clause is:
- BIT_REVERSED_POSITIVE
- SKIP RANGE skip_range_min, skip_range_max
- START COUNTER WITH start_with_counter

Options:
- sequence_kind = 'bit_reversed_positive' (Required for bit-reversed)
        """,
        "priority": "HIGH"
    },
    {
        "keywords": ["CREATE VIEW", "VIEW"],
        "topic": "CREATE VIEW Syntax",
        "rule": "Syntax for creating views. Security type (INVOKER/DEFINER) is important.",
        "syntax": """
{ CREATE VIEW | CREATE OR REPLACE VIEW } view_name
SQL SECURITY { INVOKER | DEFINER }
AS query
        """,
        "priority": "MEDIUM"
    },
    {
        "keywords": ["ALTER TABLE", "ALTER"],
        "topic": "ALTER TABLE Syntax",
        "rule": "Syntax for modifying existing tables.",
        "syntax": """
ALTER TABLE table_name action

where action is:
- ADD SYNONYM synonym
- DROP SYNONYM synonym
- RENAME TO new_table_name [, ADD SYNONYM synonym]
- ADD [ COLUMN ] [ IF NOT EXISTS] column_name data_type [ column_expression ] [ options_def ]
- DROP [ COLUMN ] column_name
- ADD table_constraint
- DROP CONSTRAINT constraint_name
- SET ON DELETE { CASCADE | NO ACTION }
- SET INTERLEAVE IN [ PARENT ] parent_table_name [ ON DELETE { CASCADE | NO ACTION } ]
- ALTER [ COLUMN ] column_name { data_type [ NOT NULL ] [ DEFAULT ( expression ) | ... ] | SET OPTIONS (...) }
- ADD ROW DELETION POLICY (...)
- DROP ROW DELETION POLICY
        """,
        "priority": "MEDIUM"
    },
    {
        "keywords": ["INT", "INTEGER", "VARCHAR", "TEXT", "BOOLEAN", "BLOB", "NUMERIC", "DECIMAL"],
        "topic": "Spanner Data Types",
        "rule": "Valid Spanner Scalar Types.",
        "syntax": """
{ BOOL | INT64 | FLOAT32 | FLOAT64 | NUMERIC | STRING( length ) | JSON | BYTES( length ) | DATE | TIMESTAMP }

length: { int64_value | MAX }
MAX for STRING is 2,621,440 characters.
MAX for BYTES is 10,485,760 bytes.
        """,
        "priority": "HIGH"
    }
]
